FROM ojimah:base
MAINTAINER ojimah

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ruby2.1
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ruby2.1-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ruby2.1-doc

RUN gem install bundler
