FROM ojimah:base
MAINTAINER ojimah

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-scipy
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-pandas
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-matplotlib
